branches:
    only: 
        - master

language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - "sudo apt-get install -y libffi-dev"
    - "pip install -r requirements.txt"
    - "export PYTHONPATH=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH"
    - "mkdir $HOME/lib"
    - "mkdir $HOME/lib/python$TRAVIS_PYTHON_VERSION"
    - "mkdir $HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages"

cache:
    - pip: true

install: "python setup.py install --prefix=$HOME"

script: 
    - "cd tests"
    - "nosetests"
