branches:
    only: 
        - master

language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - "sudo apt-get install -y libffi-dev"
    - "pip install numpy"
    - "pip install pandas"

cache:
    - pip: true

install: "sudo python setup.py install"

script: "cd tests && nosetests"
