branches:
    only: 
        - master

language: python

python:
    #- "2.6"
    - "2.7"
    #- "3.4"
    #- "3.5"

before_install:
    - "sudo apt-get install -y libffi-dev"
    - "sudo pip install numpy==1.10"
    - "sudo pip install pandas==0.18"

cache:
    - pip: true

install: "sudo python setup.py install"

script: 
    - "cd tests"
    - "echo $PYTHONPATH"
    - "ls -l /usr/local/lib/python2.7/dist-packages/"
    - "python -c 'import sys; print(sys.path)'"
    - "nosetests"
